#!/usr/bin/env bash

set -euxo pipefail 

APP_NAME='~'
action=$1

. ~/.nvm/nvm.sh 

nvm use 

case $action in

  start)
    yarn 
    yarn build 
    pm2 start --name "$APP_NAME" 'PORT=3002 node ./.output/server/index.mjs'
    ;;

  restart)
    yarn 
    yarn build 
    pm2 restart "$APP_NAME"
    ;;

  stop)
    pm2 stop "$APP_NAME"
    ;;

  kill)
    pm2 delete "$APP_NAME"
    ;;

  *)
    echo "unknown run command"    
    ;;
esac

